void print_number(int n);
void print_triangle(int size);
void print_square(int size);
void print_diagonal(int n);
void print_line(int n);
void more_numbers(void);
void print_most_numbers(void);
int _putchar(char c);
void print_numbers(void);
int mul(int a, int b);
int _isdigit(int c);
int _isupper(int c);
